### ISSUE TITLE
Server Sizing

### ISSUE THREAD

**Issue by felopla** [maths/stack_util_maximapool#16]
Hi friends, 

I would like to ask your help to sizing the server in that I have installed Maxima_Pool.

Which machine do we need, to work without problems with this scenario: 
  - 250 posible users. 
  - We would like to sizing the server to have at least 50 concurrent users.

Also, I would like to have your recommendations about the `max pool` and the `min pool` that we will need to set up to have the optimal configuration according our scenario.  

Thanks in advance for your help.

Kind regards
      Felipe López P.

**Comment by aharjula** [comment]
Oh depends on so many things... the most important being your own understanding of your real or virtual hardware. Anyway go for 2 CPU cores and 4GB RAM it should be enough as long as the machine does not do anything else. Start with the min.pool same as the max.pool to find out how many processes you can fit into the RAM, increase those values until you have filled 80-90% of the RAM, even higher if you know what you are doing. Once you have found a suitable max value drop the min value down to about 80 that is a random number that should be enough to handle the initial usage spike when those 50 concurrent users start using the system, the pool will then grow itself to it's max value but it is senseless to waste electricity to keep the pool full all the time. 

You will also need to check the parameter named "pool.start.limit" which may be a bit high for just two cores if the MaximaPool machines load spikes too high during servlet load (the first request to the servlet start the filling of the pool, as before that the servlet has not even been loaded) decrease that parameter, or increase the number of cores.

As 50 concurrent users is already a substantial amount do make sure you have done all the typical optimisation steps related to maxima recommended in [STACK documentation](https://github.com/maths/moodle-qtype_stack/blob/master/doc/en/CAS/Optimising_Maxima.md).

If you have the resources and possibility always build two MaximaPool servers and put a load-balancer in front of them, that way you can always upgrade the other server while the other one keeps serving your system and it is also simple to add servers behind the load-balancer. Nginx or Apache servers can easily be configured to act as such an load balancer, and as the nodes running STACK already have such servers they can also host those load-balancers...

If you are running on vmware do not increase the number of cores too high on KVM go for cores, in any case don't bother going too far beyond 8GB RAM as at that point the memory can hold so many processes that your cores will be using all their time checking on those processes, which is pointless.

**Comment by felopla** [comment]
Thanks for your help!

 In first place, with your recommendation, I will test in an VM and then we will buy it a real server.

I hope not bother you again!  :)

Have a good week.

Kind regards
       Felipe López P.
