### ISSUE TITLE
Syntax error??

### ISSUE THREAD

**Issue by t6nis** [maths/stack_util_maximapool#27]
Hello!

Trying to make maximapool work. 
STACK 4.1 and Moodle 3.1.9 are working and healthcheck shows at the bottom:

  | unix
-- | --
OK | You have chosen the "default" version of Maxima, so no Maxima version checking is being done. Your raw connection is actually using version "5.41.0" (41.0). CAS returned data as expected. You have a live connection to the CAS.
OK | Maxima image created at: timeout --kill-after=10s 10s /usr/lib/clisp-2.49/base/lisp.run -q -M (..path)/moodledata/stack/maxima_opt_auto.mem
OK | Correct and expected STACK-Maxima library version being used (2017121800).
  | CAS results are not being cached.

When i execute - (..path)/moodledata/stack/maxima_opt_auto.mem from command line or low level health check i get this - 
"(..path)/moodledata/stack/maxima_opt_auto.mem: 1: ..path/moodledata/stack/maxima_opt_auto.mem: Syntax error: "(" unexpected"

Any ideas?

Maxima:
Maxima 5.41.0 http://maxima.sourceforge.net
using Lisp CLISP 2.49.60+ (2017-06-25)
Distributed under the GNU Public License. See the file COPYING.
Dedicated to the memory of William Schelter.
The function bug_report() provides bug reporting information.

**Comment by aharjula** [comment]
Syntax error: "(" unexpected

Surely, your command line contains no `(` char that would cause that error? What is the raw command in your process config? Feel free to change random chars in the path if you need to obfuscate but don't hide the form i.e. are there spaces or other special chars there...

In any case first try to get that command working to find out if this is a MaximaPool issue. `lisp.run -q -M maxima_opt_auto.mem` is basically the form of the command as long as the paths have been prefixed to the lisp.run and the image and you are using CLISP.

**Comment by t6nis** [comment]
Ok here is the full command - 
user@maxima:/var/lib/maximapool/2017121800$ sudo /usr/lib/clisp-2.49/base/lisp.run -q -M /opt/veebid/vhosts/moodle.ut.ee/moodledata/stack/maxima_opt_auto.mem
/usr/lib/clisp-2.49/base/lisp.run: initialization file `/opt/veebid/vhosts/moodle.ut.ee/moodledata/stack/maxima_opt_auto.mem' was not created by this version of CLISP runtime

Although if i delete maxima_opt_auto.mem, the healthcheck creates it again. I suppose it creates using the same CLISP version.

**Comment by aharjula** [comment]
It might be that the healtcheck just fails in the image creation? If you move the image to another machine which would be sensible for a MaximaPool install there may be numerous other things that change with the lisp runtime.

Typically, people create the image manually when using MaximaPool as the Pool normally presides on another machine. [Try creating your own memory image.](https://github.com/maths/moodle-qtype_stack/blob/master/doc/en/CAS/Optimising_Maxima.md). Personally, I do it like this:
 - I run healtcheck with "Linux" and copy the maximalocal.mac file to the directory where my process.conf is.
 - I also copy the /question/type/stack/stack/maxima directory there.
 - Then I modify the paths in the maximalocal.mac to point into that maxima directory.
 - And generate the image as guided, but loading just that maximalocal.mac (it loads stackmaxima... as it is for "Linux" and not for optimized), although again I place the image to the directory with the process.conf, and point the command to it.

**Comment by t6nis** [comment]
Thank you for your feedback! 

I got this now working but i had to compile Maxima image from scratch(changed from 5.41.0 to 5.38.1) using this tutorial - https://github.com/maths/moodle-qtype_stack/blob/master/doc/en/CAS/Optimising_Maxima.md#compiling-a-maxima-image (Ubuntu) part.

The problem before was that i downloaded a prebuilt Maxima image with clisp and that throwed the error message "was not created by this version of CLISP". 

CLISP version was before 
using Lisp CLISP 2.49.60+ (2017-06-25) - that was wrong..

Now it is:
using Lisp CLISP 2.49 (2010-07-07)  and everything is working.
