### ISSUE TITLE
HTTP Status 500 – Internal Server Error

### ISSUE THREAD

**Issue by kassbohm** [maths/stack_util_maximapool#37]
I have installed as described in your README (I think).

My observations:

1. When I run the **Low-Level** Health-Check: Maxima is started and then has a timeout after 2 seconds or so.
2. When I run the **High-Level** Health-Check: I get a  HTTP Status 500 – Internal Server Error, see output below.
3. When I **Evaluate 1+1;** I get no response at all.

I have read your Troubleshooting-Section, but I cannot figure it out. Any hints about what the problem might be?

![1](https://user-images.githubusercontent.com/1640233/144841425-82f2b919-10de-4447-92e6-a8718bc60b36.PNG)

```
Type Status Report

Message <p>Process timed out.</p><pre>java.lang.RuntimeException: Process timed out. at fi.aalto.maximapool.MaximaProcess.waitForOutput(MaximaProcess.java:218) at fi.aalto.maximapool.MaximaProcess.<init>(MaximaProcess.java:80) at fi.aalto.maximapool.ProcessPool.makeProcess(ProcessPool.java:132) at fi.aalto.maximapool.PoolCoordinator.makeProcess(PoolCoordinator.java:199) at fi.aalto.maximapool.MaximaServlet.doHealthcheckHighLevel(MaximaServlet.java:370) at fi.aalto.maximapool.MaximaServlet.doGet(MaximaServlet.java:138) at javax.servlet.http.HttpServlet.service(HttpServlet.java:635) at javax.servlet.http.HttpServlet.service(HttpServlet.java:742) at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231) at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52) at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:200) at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96) at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:493) at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:137) at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:81) at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:660) at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87) at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343) at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:798) at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66) at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:806) at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1498) at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49) at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) at java.base/java.lang.Thread.run(Thread.java:829) </pre>

Description The server encountered an unexpected condition that prevented it from fulfilling the request.

```

**Comment by aharjula** [comment]
Do you have any particular reason for loading `/var/lib/tomcat8` (the file to load row in the screenshot) into the Maxima process? If that is a maxima script with a truly oddly chosen path all is fine, but to me, that seems quite odd.

Typically, people either use built images and do not need to load anything at all into the process, or load the `maximalocal.mac` file in the case of STACK whether they need or not. In your case, you are probably going for an image as you are looking for "Maxima restarted" and then intend to also check for the load with that path to "maximalocal.mac".

**Comment by kassbohm** [comment]
I have no reason to do this. This must have happened unintentionally. In file process.conf, I have now changed these two lines:
```
# A file to load to maxima using load(""); set to false or empty if not needed
# extra.file = "/var/lib/maximapool/2020120600/maximalocal.mac"

So that I have no extra.file to load... This leads to this state:

```
![2](https://user-images.githubusercontent.com/1640233/144863469-a5f9d20c-c029-4895-8e07-177103d85d73.png)

Still: Something is wrong... because I get a similar error message.

And also: There are many processes initiated...

And idea?

**Comment by kassbohm** [comment]
all tomcat8 processes:
```
tomcat8   4738  2769  0 17:44 ?        00:00:00 /usr/lib/maxima/5.41.0/binary-gcl/maxima -eval (cl-user::run) -f --
tomcat8   4816  2769  0 17:44 ?        00:00:00 /usr/lib/maxima/5.41.0/binary-gcl/maxima -eval (cl-user::run) -f --
tomcat8   4849  2769  0 17:44 ?        00:00:00 /usr/lib/maxima/5.41.0/binary-gcl/maxima -eval (cl-user::run) -f --
tomcat8   4904  2769  0 17:44 ?        00:00:00 /usr/lib/maxima/5.41.0/binary-gcl/maxima -eval (cl-user::run) -f --
tomcat8   4932  2769  0 17:44 ?        00:00:00 /usr/lib/maxima/5.41.0/binary-gcl/maxima -eval (cl-user::run) -f --
tomcat8   5020  2769  0 17:45 ?        00:00:00 /usr/lib/maxima/5.41.0/binary-gcl/maxima -eval (cl-user::run) -f --
tomcat8   5048  2769  0 17:45 ?        00:00:00 /usr/lib/maxima/5.41.0/binary-gcl/maxima -eval (cl-user::run) -f --
tomcat8   5076  2769  0 17:45 ?        00:00:00 /usr/lib/maxima/5.41.0/binary-gcl/maxima -eval (cl-user::run) -f --
...
```

**Comment by aharjula** [comment]
So you are starting `/usr/bin/maxima` and yet you expect it to print out "Maxima restarted", you do not get that output unless you are restarting a saved memory image. The pool is simply waiting for them to give a specific output which is unlikely to happen. 

Just to confirm, are you aiming to use this with STACK? Do you have a memory image as described [here](https://docs.stack-assessment.org/en/CAS/Optimising_Maxima/), that you are restarting? If you have an image the command line would be something different.

If you are not going for STACK you would simply change the "Started test string" to `(%i1)` and normal Maxima would simply work. With STACK you want to use images or do the full loading of the maximalocal.mac script.

**Comment by kassbohm** [comment]
Ok, thank you. Just now I understand.
I did want to use maximapool with STACK. But I am not focusing on performance for now. All I wanted to do is use STACK on one server - and MAXIMA on another...
Sorry about that I did not read the instructions carefully enough.

**Comment by aharjula** [comment]
Indeed the key detail to note is that when using MaximaPool or GoeMaxima one will need to setup the Maxima environment by doing the loading of the STACK specific scripts as an pre-loaded image or by loading them in during process startup, as STACK will not do that for you when running on separate servers as it cannot know how to load those files into the process. As that setup is something that varies and where people may wish to do some modifications this exactly easy, and the guides have been written by people with specific ideas about how this should work in their use cases.

Anyway assuming that this is now done and will close the issue.
